package io.harbor.example.domain.order;

import io.harbor.api.LazyRef;
import io.harbor.api.annotations.*;
import io.harbor.api.dialect.StandardDialects;
import io.harbor.api.metadata.EnumMappingType;
import io.harbor.core.sql.OffsetDateTimeAsTimestampTypeHandler;
import io.harbor.example.domain.order.dto.Order;
import io.harbor.example.domain.order.dto.OrderStatus;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.OffsetDateTime;

@Entity(table = "orders")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
class OrderEntity {

    @Id
    @AutoGenerated
    private Long id;

    @Column(nullable = false)
    private Long customerId;

    @Column(nullable = false)
    @Enumerated(EnumMappingType.ORDINAL)
    private OrderStatus status;

    @OneToOne(joinColumns = @JoinColumn(name = "order_id", fieldType = Long.class))
    private LazyRef<OrderProductEntity> orderProduct;

    @Column(nullable = false)
    @TypeHandler(dialect = StandardDialects.MARIADB, value = OffsetDateTimeAsTimestampTypeHandler.class)
    @TypeHandler(dialect = StandardDialects.MYSQL, value = OffsetDateTimeAsTimestampTypeHandler.class)
    private OffsetDateTime creationDate;

    @Column(nullable = true)
    @TypeHandler(dialect = StandardDialects.MARIADB, value = OffsetDateTimeAsTimestampTypeHandler.class)
    @TypeHandler(dialect = StandardDialects.MYSQL, value = OffsetDateTimeAsTimestampTypeHandler.class)
    private OffsetDateTime completeDate;

    Order toDto() {
        return new Order(
                id,
                customerId,
                status,
                orderProduct.get().getSeries(),
                orderProduct.get().getCode(),
                orderProduct.get().getTitle(),
                orderProduct.get().getNetPrice(),
                orderProduct.get().getGrossPrice(),
                orderProduct.get().getSnapshotDateTime(),
                creationDate,
                completeDate
        );
    }
}
