package io.harbor.example.domain.user;

import io.harbor.api.annotations.*;
import io.harbor.example.domain.user.dto.User;
import io.harbor.example.domain.user.dto.UserType;
import io.harbor.example.domain.user.dto.command.UserCreateCommand;
import io.harbor.example.domain.user.dto.command.UserUpdateCommand;
import io.harbor.example.shared.model.AddressEmbedded;
import io.harbor.example.shared.model.CallbackLog;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

@Entity(table = "users")
@NoArgsConstructor
@AllArgsConstructor
@Getter
class UserEntity {

    @Id
    @AutoGenerated
    private Long id;

    @Column(updatable = false, nullable = false)
    private String email;

    @Column(nullable = false)
    @Enumerated
    private UserType type;

    @Column(nullable = false)
    private boolean active;

    @Embedded(tableFieldNamePrefix = "residential")
    @AttributeOverrides({
            @AttributeOverride(name = "address", column = @Column(name = "residential_address", nullable = true)),
            @AttributeOverride(name = "town", column = @Column(name = "residential_town", nullable = true)),
            @AttributeOverride(name = "buildingNo", column = @Column(name = "residential_building_no", nullable = true)),
            @AttributeOverride(name = "country", column = @Column(name = "residential_country", nullable = true))
    })
    private AddressEmbedded residentialAddress;

    @Embedded(tableFieldNamePrefix = "contact")
    @AttributeOverride(name = "address", column = @Column(name = "contact_address", nullable = true))
    @AttributeOverride(name = "town", column = @Column(name = "contact_town", nullable = true))
    @AttributeOverride(name = "buildingNo", column = @Column(name = "contact_building_no", nullable = true))
    @AttributeOverride(name = "country", column = @Column(name = "contact_country", nullable = true))
    private AddressEmbedded contactAddress;

    @ManyToMany(
            table = "users_roles",
            joinColumns = @JoinColumn(name = "user_id", fieldType = Long.class),
            inverseJoinColumns = @JoinColumn(name = "role_id", fieldType = UUID.class)
    )
    private Set<UUID> rolesIds;

    static UserEntity of(@NonNull UserCreateCommand command) {
        return new UserEntity(
                null,
                command.getEmail(),
                command.getType(),
                command.isActive(),
                AddressEmbedded.of(command.getResidentialAddress()),
                AddressEmbedded.of(command.getContactAddress()),
                new HashSet<>(command.getRolesIds())
        );
    }

    @PreInsert
    private void validateEmailOnInsert() {
        validateEmail("Invalid email: ");
    }

    @PreUpdate
    private void validateEmailOnUpdate() {
        validateEmail("Invalid email on update: ");
    }

    @PreDelete
    private void validateEmailOnDelete() {
        validateEmail("Invalid email on delete: ");
    }

    private void validateEmail(String messagePrefix) {
        if (email == null || !email.contains("@")) {
            throw new IllegalArgumentException(messagePrefix + email);
        }
    }

    @PostInsert
    private void logPostInsert() {
        CallbackLog.record("user post-insert: " + email);
    }

    @PostUpdate
    private void logPostUpdate() {
        CallbackLog.record("user post-update: " + email);
    }

    @PostDelete
    private void logPostDelete() {
        CallbackLog.record("user post-delete: " + email);
    }

    void update(@NonNull UserUpdateCommand command) {
        this.type = command.getType();
        this.active = command.isActive();
        this.residentialAddress.update(command.getResidentialAddress());
        this.contactAddress.update(command.getContactAddress());
        this.rolesIds.clear();
        this.rolesIds.addAll(command.getRolesIds());
    }

    void updateEmail(@NonNull String email) {
        this.email = email;
    }

    User toDto() {
        return new User(
                id,
                email,
                type,
                active,
                residentialAddress.toDto(),
                contactAddress.toDto(),
                new HashSet<>(rolesIds)
        );
    }
}
